//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobsDescription
    {
        public int Id { get; set; }
        public string jobDes { get; set; }
        public string solution { get; set; }
        public Nullable<int> solutionCount { get; set; }
        public string clientName { get; set; }
        public string filename { get; set; }
    }
}
